const BUILDING_CODES = {
    COVE: "COVE",
    SUB: "SUB",
    BOOKSTORE: "BOOK",
    MACLAUREN: "MAC",
    JAMIE_CASSELS_CENTER: "JCC",
    CLEARIHUE: "CLE",
    GRADUATE_BUILDING: "GSC",
    MCPHERSON_LIBRARY: "LIB",
};

export { BUILDING_CODES };